apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gingeroak-com-tls
spec:
  secretName: gingeroak-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gingeroak.com
  dnsNames:
    - gingeroak.com
    - www.gingeroak.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - gingeroak.com
          - www.gingeroak.com
